### ISSUE TITLE
Have you got good result

### ISSUE THREAD

**Issue by hdmjdp** [hcy71o/SNAC#1]
In my experiments, the wav generated is not similar as the ref audio

**Comment by hcy71o** [comment]
Did you use VCTK? 
When I experimented with my personal VITS-based zero-shot model other than this model, SNAC performed better than conventional global conditioning technique.

**Comment by hdmjdp** [comment]
> Did you use VCTK? When I experimented with my personal VITS-based zero-shot model other than this model, SNAC performed better than conventional global conditioning technique.

No, I used my own data (chinese dataset).  How many epochs you train?

**Comment by hcy71o** [comment]
I trained 800k steps with VCTK, and it produces natural speech more earlier (even in 200k steps / 1250 epochs).
However, I also failed to obtain good performance when I only used LibriTTS training set.

**Comment by cnlinxi** [comment]
> I trained 800k steps with VCTK, and it produces natural speech more earlier (even in 200k steps / 1250 epochs). However, I also failed to obtain good performance when I only used LibriTTS training set.

Why say `failed to obtain good performance when I only used LibriTTS training set`? In your paper, SNAC performs significantly better than other baselines on LibriTTS.
