### ISSUE TITLE
Proposed+REF+FLOW ?

### ISSUE THREAD

**Issue by francqz31** [hcy71o/SNAC#2]
Hello, are there any intensions to implement "Proposed+REF+FLOW" along with the already implemented "Baseline + REF + FLOW"

Thanks in advance.

**Comment by hcy71o** [comment]
Later if time permits. Or you can easily implement by using original VITS code (just revise normalizing flow and its determinant computation part)!

**Comment by hdmjdp** [comment]
@hcy71o but your code include SNAC layer, so why you said your code is only baseline version?

**Comment by hcy71o** [comment]
Sorry I misspelled it. The implemented model is "Proposed+REF+FLOW". 
I revised the readme. Thanks for letting me know
