### ISSUE TITLE
kl loss 발산 관련 

### ISSUE THREAD

**Issue by KinamSalad** [hcy71o/SNAC#4]
안녕하세요. SNAC 논문 잘 봤습니다! 
현재 저는 proposed + pre-trained + flow 형태로 만들고 있는데요.
snac관련 부분은 해당 코드를 그대로 가져와서 구현했습니다(loss도 변경완료했습니다)
그런데 kl loss가 계속 nan으로 발산하는데 혹시 추가적으로 이런현상을 제어하기위해 코드변경하신부분이 있으신가요?
아니면 이런 현상을 겪어 보신적이 있으시면 해결방법 알려주시면 감사하겠습니다. 
감사합니다.

**Comment by hcy71o** [comment]
안녕하세요, 우선 저는 SNAC 논문 저자가 아닙니다! ㅎㅎ
저도 가끔씩 해당 현상이 발생했는데, SNAC과 무관하게 VITS를 제로 샷 세팅으로 학습할 때 나타나는 것 같아요. 
정확한 원인은 찾지 못했고, DB 질이 안좋을 때 MAS/duration predictor 학습도 같이 실패하면서 nan이 떴던 것으로 기억하는데,
일차적으로 Duration predictor에서 speaker embedding 넣지 않는 방식(speaker-independent duration)으로 진행해보시거나, 우선적으로 VCTK DB만 사용해 실험해보셔도 좋을 것 같습니다.
